### 머신러닝 개념(ML)


- 데이터를 기반으로 패턴을 학습하고 결과를 추론하는 알고리즘 기법
- 지도학습(supervised Learning), 비지도학습(Un- Supervised Learning) {구분 기준은 정답의 존재여부}
- 지도학습(분류, 회귀), 비지도학습(클러스터링, 차원축소) (회귀 = 예측, 분류 = 나누는 것)
           분류는 정답의 타입이 범주형 회귀는 숫자가 연속되는값(예측)/ 
           클러스터링 = 군집화, 차원축소 = PCA 비지도학습을 하는데 있어 여러개의 feature를 줄이는 것


### 머신러닝 용어(데이터의 형식 : DataFrame)

- 피처(feature) : 데이터의 일반 속성
- 레일블, 클래스, 타겟 값, 결정 값 : 정답 데이터

In [217]:
import numpy  as np
import pandas as pd

print('numpy  version -', np.__version__)
print('pandas version -', pd.__version__)

numpy  version - 1.20.3
pandas version - 1.3.4

In [218]:
import sklearn
from   sklearn.datasets import load_iris
print('sklearn version -', sklearn.__version__)

sklearn version - 0.24.2

In [219]:
iris = load_iris()
print('type -', type(iris))
print('keys -', iris.keys())

type - <class 'sklearn.utils.Bunch'>
keys - dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [220]:
print('data-', iris.data)
print('data type-', type(iris.data))

data- [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.1 1.3]
 [6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.  2.2 5.  1.5]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
data type- <class 'numpy.ndarray'>

In [221]:
print('target -', iris.target)
print('target type-', type(iris.target))
print()
print('feature_names-', iris.feature_names)
print('feature_names type-', type(iris.feature_names))

target - [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
target type- <class 'numpy.ndarray'>

feature_names- ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
feature_names type- <class 'list'>

In [222]:
print('feature, target를 이용해서 데이터 프레임을 만들어보자 -')
print()
print()

feature, target를 이용해서 데이터 프레임을 만들어보자 -

In [223]:
iris_frm = pd.DataFrame(data = iris.data,
                       columns = iris.feature_names)
iris_frm

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

#### 지도학습 - 분류(classification)
- step 01. 데이터 분리(training data, test data)
- step 02. 학습 데이터를 기반으로 ML(머신러닝) 알고리즘을 적용해 학습 모델을 생성{머신러닝이 적용된기계=모델}
- step 03. 테스트 데이터를 기반으로 분류 예측을 수행
- step 04. 모델의 성능 평가

In [224]:
from sklearn.model_selection import train_test_split
from sklearn.tree            import DecisionTreeClassifier
from sklearn.metrics         import accuracy_score

In [225]:
print('step 01.')      #사이킷런은 x train test, y train test  하지만 텐서플로우는 x y train  x y test 순
print()

X_train, X_test, y_train, y_test = train_test_split(iris.data,
                                                   iris.target,
                                                   test_size=0.2, # 저절로 트레인 사이즈는0.8이된다
                                                   shuffle = True,
                                                   random_state = 100) # 100은 임의의 수치

step 01.

In [226]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [227]:
print('train data -', X_train)
print()
print('train target -', y_train)

train data - [[5.5 2.4 3.7 1. ]
 [5.7 2.8 4.1 1.3]
 [6.  2.2 5.  1.5]
 [4.8 3.  1.4 0.1]
 [5.4 3.9 1.3 0.4]
 [6.4 3.2 4.5 1.5]
 [5.1 3.8 1.6 0.2]
 [5.5 2.5 4.  1.3]
 [6.3 3.4 5.6 2.4]
 [5.8 2.8 5.1 2.4]
 [4.5 2.3 1.3 0.3]
 [5.5 2.6 4.4 1.2]
 [7.1 3.  5.9 2.1]
 [7.2 3.6 6.1 2.5]
 [4.9 3.6 1.4 0.1]
 [4.6 3.4 1.4 0.3]
 [5.  3.  1.6 0.2]
 [5.1 3.7 1.5 0.4]
 [5.8 2.6 4.  1.2]
 [4.9 3.1 1.5 0.1]
 [5.1 3.3 1.7 0.5]
 [5.  3.2 1.2 0.2]
 [6.5 2.8 4.6 1.5]
 [7.9 3.8 6.4 2. ]
 [6.1 3.  4.9 1.8]
 [5.4 3.  4.5 1.5]
 [6.4 2.7 5.3 1.9]
 [5.7 2.9 4.2 1.3]
 [7.7 3.8 6.7 2.2]
 [6.5 3.2 5.1 2. ]
 [5.8 2.7 3.9 1.2]
 [4.6 3.6 1.  0.2]
 [6.9 3.1 5.4 2.1]
 [6.7 3.3 5.7 2.1]
 [6.3 2.8 5.1 1.5]
 [5.5 4.2 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [5.8 2.7 5.1 1.9]
 [5.4 3.9 1.7 0.4]
 [5.5 3.5 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [6.9 3.1 4.9 1.5]
 [6.5 3.  5.8 2.2]
 [6.7 3.3 5.7 2.5]
 [6.1 2.6 5.6 1.4]
 [5.4 3.7 1.5 0.2]
 [6.  3.4 4.5 1.6]
 [5.9 3.2 4.8 1.8]
 [4.6 3.1 1.5 0.2]
 [6.8 2.8 4.8 1.4]
 [4.9 2.4 3.3 1. ]
 [6.2 2.8 4.8 1.8]
 [5.1 3.5 1.4 0.2]
 [6.  2.9 4.5 1.5]
 [5.6 3.  4.1 1.3]
 [6.  2.7 5.1 1.6]
 [7.  3.2 4.7 1.4]
 [6.2 2.2 4.5 1.5]
 [5.7 3.  4.2 1.2]
 [6.4 2.8 5.6 2.2]
 [5.7 2.5 5.  2. ]
 [4.3 3.  1.1 0.1]
 [6.3 2.5 4.9 1.5]
 [5.1 3.5 1.4 0.3]
 [6.4 2.9 4.3 1.3]
 [7.2 3.  5.8 1.6]
 [6.4 3.1 5.5 1.8]
 [4.9 2.5 4.5 1.7]
 [5.6 2.9 3.6 1.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.9 0.4]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.6 2.8 4.9 2. ]
 [5.3 3.7 1.5 0.2]
 [4.8 3.1 1.6 0.2]
 [6.3 3.3 4.7 1.6]
 [5.2 3.5 1.5 0.2]
 [6.7 3.1 5.6 2.4]
 [6.1 2.9 4.7 1.4]
 [6.9 3.1 5.1 2.3]
 [5.1 3.8 1.5 0.3]
 [5.8 2.7 5.1 1.9]
 [7.6 3.  6.6 2.1]
 [4.7 3.2 1.3 0.2]
 [5.5 2.4 3.8 1.1]
 [6.1 2.8 4.  1.3]
 [5.7 2.8 4.5 1.3]
 [6.8 3.2 5.9 2.3]
 [5.9 3.  4.2 1.5]
 [6.7 3.1 4.4 1.4]
 [4.6 3.2 1.4 0.2]
 [5.  3.3 1.4 0.2]
 [5.  3.4 1.5 0.2]
 [6.5 3.  5.2 2. ]
 [5.2 2.7 3.9 1.4]
 [6.1 3.  4.6 1.4]
 [5.  3.6 1.4 0.2]
 [6.3 3.3 6.  2.5]
 [6.7 2.5 5.8 1.8]
 [7.4 2.8 6.1 1.9]
 [6.7 3.1 4.7 1.5]
 [5.  2.3 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.  2.  3.5 1. ]
 [7.3 2.9 6.3 1.8]
 [6.2 3.4 5.4 2.3]
 [4.9 3.1 1.5 0.2]
 [5.8 4.  1.2 0.2]
 [5.6 3.  4.5 1.5]
 [5.5 2.3 4.  1.3]
 [5.1 2.5 3.  1.1]
 [5.6 2.7 4.2 1.3]
 [6.  3.  4.8 1.8]
 [5.7 2.6 3.5 1. ]
 [6.3 2.3 4.4 1.3]
 [6.3 2.9 5.6 1.8]
 [5.8 2.7 4.1 1. ]
 [4.8 3.4 1.9 0.2]
 [4.4 2.9 1.4 0.2]]

train target - [1 1 2 0 0 1 0 1 2 2 0 1 2 2 0 0 0 0 1 0 0 0 1 2 2 1 2 1 2 2 1 0 2 2 2 0 0
 2 0 0 0 1 2 2 2 0 1 1 0 1 1 2 0 1 1 1 1 1 1 2 2 0 1 0 1 2 2 2 1 0 0 0 0 2
 0 0 1 0 2 1 2 0 2 2 0 1 1 1 2 1 1 0 0 0 2 1 1 0 2 2 2 1 1 1 1 2 2 0 0 1 1
 1 1 2 1 1 2 1 0 0]

In [228]:
print('test data -', X_test)
print()
print('test target -', y_test)

test data - [[6.4 2.8 5.6 2.1]
 [4.8 3.4 1.6 0.2]
 [7.7 2.6 6.9 2.3]
 [5.7 4.4 1.5 0.4]
 [6.3 2.7 4.9 1.8]
 [7.7 3.  6.1 2.3]
 [5.2 4.1 1.5 0.1]
 [4.9 3.  1.4 0.2]
 [6.5 3.  5.5 1.8]
 [4.8 3.  1.4 0.3]
 [5.  3.5 1.3 0.3]
 [6.4 3.2 5.3 2.3]
 [5.  3.4 1.6 0.4]
 [5.2 3.4 1.4 0.2]
 [6.7 3.  5.2 2.3]
 [6.2 2.9 4.3 1.3]
 [6.  2.2 4.  1. ]
 [6.7 3.  5.  1.7]
 [7.7 2.8 6.7 2. ]
 [6.8 3.  5.5 2.1]
 [7.2 3.2 6.  1.8]
 [5.4 3.4 1.5 0.4]
 [6.3 2.5 5.  1.9]
 [4.7 3.2 1.6 0.2]
 [5.6 2.5 3.9 1.1]
 [5.9 3.  5.1 1.8]
 [6.6 3.  4.4 1.4]
 [5.4 3.4 1.7 0.2]
 [6.1 2.8 4.7 1.2]
 [6.9 3.2 5.7 2.3]]

test target - [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 1 2 2 2 0 2 0 1 2 1 0 1 2]

In [229]:
print('step 02.')
print()
iris_dtc_model = DecisionTreeClassifier()
iris_dtc_model.fit(X_train, y_train)

step 02.

DecisionTreeClassifier()

In [230]:
print('step 03. predict()')
print()

y_pred = iris_dtc_model.predict(X_test)
print('y_test -', y_test)
print('t_pred -', y_pred)

step 03. predict()

y_test - [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 1 2 2 2 0 2 0 1 2 1 0 1 2]
t_pred - [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 2 2 2 2 0 2 0 1 2 1 0 1 2]

In [231]:
print('step 04. 예측정확도 -')
print()
print('acc -', accuracy_score(y_test, y_pred))

step 04. 예측정확도 -

acc - 0.9666666666666667

In [232]:
e = (30,)
print(type(e))

<class 'tuple'>

In [233]:
display(iris_frm)
print()
print('type-', type(iris_frm))

iris_frm['target'] = iris.target
iris_frm

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

type- <class 'pandas.core.frame.DataFrame'>

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [234]:
print('데이터 프레임 형식에서 학습 데이터와 테스트 데이터를 분리한다면? -')
print()
print('target-')
print(iris_frm['target'], type(iris_frm['target']))

데이터 프레임 형식에서 학습 데이터와 테스트 데이터를 분리한다면? -

target-
0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32 <class 'pandas.core.series.Series'>

In [235]:
print('iloc()이용해서 피처와 타겟을 추출한다면 - ')
print()

# 복붙

iris_feature_frm = iris_frm.iloc[:,:3]
# iris_feature_frm = iris_frm.iloc[:,:-1]
iris_target_frm = iris_frm.iloc[:,4]
#iris_target_frm = iris_frm.iloc[:,-1]

display(iris_feature_frm)
print()
display(iris_target_frm)
print()
print(type(iris_feature_frm),type(iris_target_frm))

iloc()이용해서 피처와 타겟을 추출한다면 -

     sepal length (cm)  sepal width (cm)  petal length (cm)
0                  5.1               3.5                1.4
1                  4.9               3.0                1.4
2                  4.7               3.2                1.3
3                  4.6               3.1                1.5
4                  5.0               3.6                1.4
..                 ...               ...                ...
145                6.7               3.0                5.2
146                6.3               2.5                5.0
147                6.5               3.0                5.2
148                6.2               3.4                5.4
149                5.9               3.0                5.1

[150 rows x 3 columns]

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>

In [236]:
iris_dtc_model = DecisionTreeClassifier()
iris_dtc_model.fit(X_train, y_train)

DecisionTreeClassifier()

In [237]:
y_pred = iris_dtc_model.predict(X_train)
print('y_test-', y_train)
print('y_pred-', y_pred, type(y_pred))

y_test- [1 1 2 0 0 1 0 1 2 2 0 1 2 2 0 0 0 0 1 0 0 0 1 2 2 1 2 1 2 2 1 0 2 2 2 0 0
 2 0 0 0 1 2 2 2 0 1 1 0 1 1 2 0 1 1 1 1 1 1 2 2 0 1 0 1 2 2 2 1 0 0 0 0 2
 0 0 1 0 2 1 2 0 2 2 0 1 1 1 2 1 1 0 0 0 2 1 1 0 2 2 2 1 1 1 1 2 2 0 0 1 1
 1 1 2 1 1 2 1 0 0]
y_pred- [1 1 2 0 0 1 0 1 2 2 0 1 2 2 0 0 0 0 1 0 0 0 1 2 2 1 2 1 2 2 1 0 2 2 2 0 0
 2 0 0 0 1 2 2 2 0 1 1 0 1 1 2 0 1 1 1 1 1 1 2 2 0 1 0 1 2 2 2 1 0 0 0 0 2
 0 0 1 0 2 1 2 0 2 2 0 1 1 1 2 1 1 0 0 0 2 1 1 0 2 2 2 1 1 1 1 2 2 0 0 1 1
 1 1 2 1 1 2 1 0 0] <class 'numpy.ndarray'>

In [238]:
acc = accuracy_score(y_train, y_pred)  # overfitting(과대적합)
print('acc-', acc)

acc- 1.0

#### 교차 검증
- 과적합(overffiting)을 방지하기 위한 방법
- 데이터의 편중을 막기 위해서
- KFold 방식

In [239]:
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score, cross_validate

In [240]:
fold_iris = load_iris()

features = fold_iris.data
label    = fold_iris.target

In [241]:
features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [242]:
label

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [243]:
print('5개의 폴더 세트를 분리하여 각 폴더 세트별 정확도를 확인해보자 -')
cv_acc = []
kfold = KFold(n_splits=5)

fold_dct_model = DecisionTreeClassifier()

for train_idx , test_idx in kfold.split(features) :
    X_train, X_val = features[train_idx], features[test_idx]
    y_train, y_val = label[train_idx], label[test_idx]
#     print('X_train -', X_val)
    fold_dct_model.fit(X_train, y_train)
    fold_pred = fold_dct_model.predict(X_val)
    
    acc = accuracy_score(y_val, fold_pred)
    print('acc-', acc)
    cv_acc.append(acc)
    pass

print('교차검증 평균 정확도-', np.mean(cv_acc))


#     print('train idx -', train_idx)
#     print('test idx  -', test_idx)

5개의 폴더 세트를 분리하여 각 폴더 세트별 정확도를 확인해보자 -
acc- 1.0
acc- 0.9666666666666667
acc- 0.8333333333333334
acc- 0.9333333333333333
acc- 0.7333333333333333
교차검증 평균 정확도- 0.8933333333333333

In [244]:
print('기존 KFold 방식의 문제점 확인 -')
print()

fold_iris_frm = pd.DataFrame(data = fold_iris.data,
                             columns = fold_iris.feature_names)
fold_iris_frm['target'] = fold_iris.target
fold_iris_frm

기존 KFold 방식의 문제점 확인 -

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [245]:
fold_iris_frm['target'].value_counts()

0    50
1    50
2    50
Name: target, dtype: int64

In [246]:
bad_fold_iris = KFold(n_splits = 3)  # 3개로 나눠서 3번째를 validation으로 쓴다

n_iter = 0

fold_dct_model = DecisionTreeClassifier()

for train_idx , test_idx in bad_fold_iris.split(fold_iris_frm) :
    n_iter += 1
    
    label_train = fold_iris_frm['target'].iloc[train_idx]
    label_val = fold_iris_frm['target'].iloc[test_idx]
    print('교차검증 횟수 -', n_iter)
    print()
    print('학습 레이블 데이터 분포 - \n', label_train)
    print('검증 레이블 데이터 분포 - \n', label_val)

교차검증 횟수 - 1

학습 레이블 데이터 분포 -
 50     1
51     1
52     1
53     1
54     1
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 100, dtype: int32
검증 레이블 데이터 분포 -
 0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
27    0
28    0
29    0
30    0
31    0
32    0
33    0
34    0
35    0
36    0
37    0
38    0
39    0
40    0
41    0
42    0
43    0
44    0
45    0
46    0
47    0
48    0
49    0
Name: target, dtype: int32
교차검증 횟수 - 2

학습 레이블 데이터 분포 -
 0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 100, dtype: int32
검증 레이블 데이터 분포 -
 50    1
51    1
52    1
53    1
54    1
55    1
56    1
57    1
58    1
59    1
60    1
61    1
62    1
63    1
64    1
65    1
66    1
67    1
68    1
69    1
70    1
71    1
72    1
73    1
74    1
75    1
76    1
77    1
78    1
79    1
80    1
81    1
82    1
83    1
84    1
85    1
86    1
87    1
88    1
89    1
90    1
91    1
92    1
93    1
94    1
95    1
96    1
97    1
98    1
99    1
Name: target, dtype: int32
교차검증 횟수 - 3

학습 레이블 데이터 분포 -
 0     0
1     0
2     0
3     0
4     0
     ..
95    1
96    1
97    1
98    1
99    1
Name: target, Length: 100, dtype: int32
검증 레이블 데이터 분포 -
 100    2
101    2
102    2
103    2
104    2
105    2
106    2
107    2
108    2
109    2
110    2
111    2
112    2
113    2
114    2
115    2
116    2
117    2
118    2
119    2
120    2
121    2
122    2
123    2
124    2
125    2
126    2
127    2
128    2
129    2
130    2
131    2
132    2
133    2
134    2
135    2
136    2
137    2
138    2
139    2
140    2
141    2
142    2
143    2
144    2
145    2
146    2
147    2
148    2
149    2
Name: target, dtype: int32

#### [실습]
- 아이리스 데이터를 이용하여 StratifiedKFold 교차검증을 진행해 보자
- random_state = 200
- StratifiedKFold(3, 5) 평균 정확도 확인

In [247]:
fold_iris = load_iris()

In [248]:
features = fold_iris.data
label = fold_iris.target

In [249]:
cv_acc = []

skf= StratifiedKFold(n_splits=5)

fold_dct_model = DecisionTreeClassifier(random_state = 200)
n_iter = 0

for train_idx , test_idx in skf.split(features, label) :
    n_iter +=1
    X_train, X_val = features[train_idx], features[test_idx]
    y_train, y_val = label[train_idx], label[test_idx]
    
print('교차검증 평균 정확도-', np,mean(cv_acc))

NameError: name 'mean' is not defined

In [250]:
print('5개의 폴더 세트를 분리하여 각 폴더 세트별 정확도를 확인해보자 -')
cv_acc = []
kfold = KFold(n_splits=5)

fold_dct_model = DecisionTreeClassifier()

for train_idx , test_idx in kfold.split(features) :
    X_train, X_val = features[train_idx], features[test_idx]
    y_train, y_val = label[train_idx], label[test_idx]
#     print('X_train -', X_val)
    fold_dct_model.fit(X_train, y_train)
    fold_pred = fold_dct_model.predict(X_val)
    
    acc = accuracy_score(y_val, fold_pred)
    print("검증 횟수 {}, 교차 검증 정확도{}, 학습 데이터 크기 {}, 검증 데이터 크기 {}".format(n_iter, acc, X_train.shape[0], X_val.shape)

SyntaxError: unexpected EOF while parsing (Temp/ipykernel_15404/977263725.py, line 22)